# Generated by Django 3.1.7 on 2021-03-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_employee',
            field=models.BooleanField(default=True, verbose_name='Действующий сотрудник'),
        ),
    ]
