version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
    - postgres_volume:/var/lib/postgresql/data

  web_simbirsoft:
    image: mvp_calculator
    container_name: mvp_calculator_container
    build: .
    env_file:
      - ./.env.dev
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done;
      python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_volume: