# Generated by Django 3.1.7 on 2021-03-04 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxСalculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('second_name', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=10, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='E-mail')),
                ('adress', models.CharField(blank=True, max_length=1000, verbose_name='Адрес')),
                ('building_adress', models.CharField(blank=True, max_length=1000, verbose_name='Адрес строительства дома')),
            ],
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_units_name', models.CharField(max_length=20, verbose_name='Наименование единицы измерения')),
            ],
        ),
        migrations.CreateModel(
            name='PriceLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Цена закупки')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Цена продажи')),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.materials', verbose_name='Материал')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название статуса')),
            ],
        ),
        migrations.CreateModel(
            name='RoofCalculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.pricelists', verbose_name='Прайс-лист')),
            ],
        ),
        migrations.AddField(
            model_name='materials',
            name='materials_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.materialstype', verbose_name='Тип материала'),
        ),
        migrations.AddField(
            model_name='materials',
            name='measurement_unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.measurementunits', verbose_name='Единицы измерения'),
        ),
        migrations.CreateModel(
            name='FoundationСalculations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.pricelists', verbose_name='Прайс-лист')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('box_calculation_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='calculator.boxсalculations', verbose_name='Расчет коробки')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.customers', verbose_name='Заказчик')),
                ('estimate_state_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculator.states', verbose_name='Cтатус сметы')),
                ('foundation_calculation_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='calculator.foundationсalculations', verbose_name='Расчет фундамента')),
            ],
        ),
    ]
