# Generated by Django 3.1.7 on 2021-03-14 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='calculator.customers', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='state_calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculation', to='calculator.calculationstate', verbose_name='Статус расчета'),
        ),
    ]
