# Generated by Django 3.1.7 on 2021-03-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20210309_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificmaterial',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='specificmaterial',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Толщина'),
        ),
        migrations.AlterField(
            model_name='specificmaterial',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='specificmaterial',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина'),
        ),
    ]
