# Generated by Django 3.1.7 on 2021-03-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20210310_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificmaterial',
            name='materials',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='specificMaterials', to='calculator.materials', verbose_name='Материал'),
            preserve_default=False,
        ),
    ]
