# Generated by Django 3.1.7 on 2021-03-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20210313_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['-data'], 'verbose_name': 'Прайс лист', 'verbose_name_plural': 'Прайс листы'},
        ),
    ]
