# Generated by Django 3.1.7 on 2021-03-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_result_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='floor',
        ),
    ]
