# Generated by Django 3.1.7 on 2021-03-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_specificmaterial_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificmaterial',
            name='materials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specific_materials', to='calculator.materials', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='specificmaterial',
            name='measurement_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specific_materials', to='calculator.measurementunit', verbose_name='Единица измерения'),
        ),
    ]
