# Generated by Django 3.1.7 on 2021-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20210313_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Шаг стоек'),
        ),
    ]
