# Generated by Django 3.1.7 on 2021-03-13 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20210313_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='calculator.calculation', verbose_name='Расчет'),
        ),
    ]
