# Generated by Django 3.1.7 on 2021-03-10 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20210310_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrameOpenings',
            new_name='FrameOpening',
        ),
        migrations.RenameModel(
            old_name='Materials',
            new_name='Material',
        ),
        migrations.RenameModel(
            old_name='Openings',
            new_name='Opening',
        ),
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
    ]
