# Generated by Django 3.1.7 on 2021-03-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_auto_20210313_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuralelementframe',
            name='OSB_for_ceiling',
        ),
        migrations.RemoveField(
            model_name='structuralelementframe',
            name='OSB_for_sub_floor',
        ),
        migrations.AddField(
            model_name='structuralelementframe',
            name='OSB_for_base_area',
            field=models.CharField(default='1', max_length=30, verbose_name='ОСБ для потолка и пола'),
        ),
        migrations.AddField(
            model_name='structuralelementframe',
            name='OSB_for_external_walls',
            field=models.CharField(default='1', max_length=30, verbose_name='ОСБ для наружных стен'),
        ),
    ]
