# Generated by Django 3.1.7 on 2021-03-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20210316_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='ед. измерения - метры (м)', max_digits=10, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='type',
            field=models.CharField(help_text='Дверные проемы внутренние, Дверные проемы внешние или Оконные проемы', max_length=50, verbose_name='Тип проема'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='wigth',
            field=models.DecimalField(decimal_places=2, help_text='ед. измерения - метры (м)', max_digits=10, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='specificmaterial',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='мм, если применимо к материалу', max_digits=10, null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='specificmaterial',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='мм, если применимо к материалу', max_digits=10, null=True, verbose_name='Толщина'),
        ),
        migrations.AlterField(
            model_name='specificmaterial',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='м3, если применимо к материалу', max_digits=10, null=True, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='specificmaterial',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='мм, если применимо к материалу', max_digits=10, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='OSB_for_base_area',
            field=models.CharField(help_text='Название материала', max_length=30, verbose_name='ОСБ для потолка и пола'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='OSB_for_external_walls',
            field=models.CharField(help_text='Название материала', max_length=30, verbose_name='ОСБ для наружных стен'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='OSB_for_interior_walls',
            field=models.CharField(help_text='Название материала', max_length=30, verbose_name='ОСБ для внутренних стен'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='base_area',
            field=models.DecimalField(decimal_places=2, help_text='ед. измерения - метры кубические (м2)', max_digits=10, verbose_name='Площадь основания'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='external_wall_thickness',
            field=models.DecimalField(decimal_places=2, help_text='ед. измерения - миллиметры (мм)', max_digits=10, verbose_name='Толщина внешних стен'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='height_of_one_floor',
            field=models.DecimalField(decimal_places=2, help_text='ед. измерения - метры (м)', max_digits=10, verbose_name='Высота одного этажа'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='insulation_base_area',
            field=models.CharField(help_text='Название материала', max_length=30, verbose_name='Утеплитель'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='insulation_external_walls',
            field=models.CharField(help_text='Название материала', max_length=30, verbose_name='Утеплитель'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='internal_wall_length',
            field=models.DecimalField(decimal_places=2, help_text='ед. измерения - метры (м)', max_digits=10, verbose_name='Длина внутренних стен'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='internal_wall_thickness',
            field=models.DecimalField(decimal_places=2, help_text='ед. измерения - миллиметры (мм)', max_digits=10, verbose_name='Толщина внутренних стен'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='overlap_thickness',
            field=models.DecimalField(decimal_places=2, help_text='ед. измерения - миллиметры (мм)', max_digits=10, verbose_name='Толщина перекрытия'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='perimeter_of_external_walls',
            field=models.DecimalField(decimal_places=2, help_text='ед. измерения - метры (м)', max_digits=10, verbose_name='Периметр внешних стен'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='steam_waterproofing_base_area',
            field=models.CharField(help_text='Название материала', max_length=30, verbose_name='Парогидроизоляция'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='steam_waterproofing_external_walls',
            field=models.CharField(help_text='Название материала', max_length=30, verbose_name='Парогидроизоляция'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='step_of_racks',
            field=models.DecimalField(decimal_places=2, help_text='ед. измерения - метры (м)', max_digits=10, verbose_name='Шаг стоек'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='windscreen_base_area',
            field=models.CharField(help_text='Название материала', max_length=30, verbose_name='Ветрозащита'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='windscreen_external_walls',
            field=models.CharField(help_text='Название материала', max_length=30, verbose_name='Ветрозащита'),
        ),
    ]
