# Generated by Django 3.1.7 on 2021-03-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20210313_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuralelementframe',
            name='insulation',
        ),
        migrations.RemoveField(
            model_name='structuralelementframe',
            name='steam_waterproofing',
        ),
        migrations.RemoveField(
            model_name='structuralelementframe',
            name='windscreen',
        ),
        migrations.AddField(
            model_name='structuralelementframe',
            name='insulation_base_area',
            field=models.CharField(default='1', max_length=30, verbose_name='Утеплитель'),
        ),
        migrations.AddField(
            model_name='structuralelementframe',
            name='insulation_external_walls',
            field=models.CharField(default='1', max_length=30, verbose_name='Утеплитель'),
        ),
        migrations.AddField(
            model_name='structuralelementframe',
            name='steam_waterproofing_base_area',
            field=models.CharField(default='1', max_length=30, verbose_name='Парогидроизоляция'),
        ),
        migrations.AddField(
            model_name='structuralelementframe',
            name='steam_waterproofing_external_walls',
            field=models.CharField(default='1', max_length=30, verbose_name='Парогидроизоляция'),
        ),
        migrations.AddField(
            model_name='structuralelementframe',
            name='windscreen_base_area',
            field=models.CharField(default='1', max_length=30, verbose_name='Ветрозащита'),
        ),
        migrations.AddField(
            model_name='structuralelementframe',
            name='windscreen_external_walls',
            field=models.CharField(default='1', max_length=30, verbose_name='Ветрозащита'),
        ),
    ]
