# Generated by Django 3.1.7 on 2021-03-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20210310_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificmaterial',
            old_name='materials',
            new_name='material',
        ),
    ]
