# Generated by Django 3.1.7 on 2021-03-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_structuralelementfoundation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structuralelementfoundation',
            old_name='calculations',
            new_name='calculation',
        ),
    ]
