# Generated by Django 3.1.7 on 2021-03-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_auto_20210320_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='calculator.structuralelementframe', verbose_name='каркас'),
        ),
    ]
