# Generated by Django 3.1.7 on 2021-03-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_auto_20210320_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameopening',
            name='frame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.structuralelementframe', verbose_name='каркас'),
        ),
        migrations.AlterField(
            model_name='frameopening',
            name='opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.opening', verbose_name='проем'),
        ),
        migrations.AlterField(
            model_name='structuralelementfoundation',
            name='calculation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_element_foundation', to='calculator.calculation', verbose_name='Расчет'),
        ),
        migrations.AlterField(
            model_name='structuralelementframe',
            name='calculations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structural_element_frame', to='calculator.calculation', verbose_name='Расчет'),
        ),
    ]
